version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx_for_chat
    volumes:
      -  ./nginx/conf.d:/etc/nginx/conf.d
      -  ./nginx/ssl.d:/etc/nginx/ssl.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - chatgpt-web
    restart: always
  chatgpt-web:
    build: ./chatgpt-web
    container_name: chatgpt-web
    restart: always